[workspace]
name = "word-ladder"
description = "The Word Ladder game exploration via the graph theory."
version = "0.1.0"
channels = ['conda-forge']
platforms = ['osx-64', 'osx-arm64']

[dependencies]
python = "~=3.10.0"
loguru = "*"
pytest = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"
nltk = ">=3.9.2,<4"
networkx = ">=3.4.2,<4"
plotly = ">=6.5.2,<7"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.15.2,<2"
pyvis = ">=0.3.2,<0.4"

[pypi-dependencies]
python-dotenv = "*"
src = { path = ".", editable = true }
kaleido = ">=1.2.0, <2"
